name: "supabase-tests"
on:
  pull_request:
  workflow_dispatch:

jobs:
  test_supabase:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      REEPAY_API_KEY: ${{ secrets.REEPAY_API_KEY }}
      REEPAY_API_URL: ${{ vars.REEPAY_API_URL }}
      DINERO_API_URL: ${{ vars.DINERO_API_URL }}
      AUTH_DINERO_URL: ${{ vars.DINERO_API_URL }}
      DINERO_ORG_ID: ${{ secrets.DINERO_ORG_ID }}
      DINERO_API_KEY: ${{ secrets.DINERO_API_KEY }}
      DINERO_CLIENT_ID: ${{ secrets.DINERO_CLIENT_ID }}
      DINERO_SECRET: ${{ secrets.DINERO_SECRET }}
      TRANSFER_PROTOCOL: ${{vars.TRANSFER_PROTOCOL }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - uses: denoland/setup-deno@v1

      - name: Concatenate files for unit testing
        run: |
          cd ${{ github.workspace }}/supabase/automation
          python concat-ext-and-seed-files.unit.py

      - name: Setup Database
        run: supabase start

      - name: Setup Database
        run: supabase db reset

      - name: Test Database
        run: supabase test db

      - name: Unit Test Edge Functions
        run: deno test --allow-env --config supabase/functions/deno.unit.json
